version: '3'
services:
  consul-server:
    image: consul:1.2.0
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"

  mongodb:
    image: mongo:latest
    container_name: "planet_mongodb"
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # --quiet

  planet-api:
    build: ../planet-service
    links:
      - consul-server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-server
      - SPRING_APPLICATION_NAME=planet-api
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - PLANET_API_SERVICE_ID= planet-api

  apache:
    build: apache
    links:
      - consul-server
    depends_on:
      - consul-server
    ports:
      - "80:80"
